import json
import os
import pytest
from nexus_db.crypto import (
    encrypt_secret,
    decrypt_secret,
    normalize_email,
    hash_email,
    mask_ip_subnet,
    normalize_user_agent,
    hash_user_agent,
    normalize_device_id,
    hash_device_id,
    generate_maas_token,
    hash_maas_token,
    preview_maas_token,
)
from nexus_db.audit import (
    compute_canonical_preimage,
    compute_entry_hash,
    verify_audit_chain,
)
from nexus_db.sanitize import sanitize_audit_data

# Load shared cross-language fixtures
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
FIXTURES_PATH = os.path.abspath(os.path.join(CURRENT_DIR, "../../fixtures/crypto-fixtures.json"))

with open(FIXTURES_PATH, "r", encoding="utf-8") as f:
    FIXTURES = json.load(f)


class TestAES256GCMParity:
    def test_decrypt_node_ciphertexts(self):
        """Python decrypts ciphertexts generated by Node.js in fixtures (D-13, D-16)."""
        for v in FIXTURES["encryption_vectors"]:
            decrypted = decrypt_secret(v["encrypted"], v["key_hex"])
            assert decrypted == v["plaintext"]

    def test_encrypt_matches_fixtures(self):
        """Python encryption with fixed IV matches fixture ciphertext exactly (D-13, D-16)."""
        for v in FIXTURES["encryption_vectors"]:
            encrypted = encrypt_secret(v["plaintext"], v["key_hex"], v["iv_hex"])
            assert encrypted == v["encrypted"]

    def test_roundtrip_random_iv(self):
        """Python encryption and decryption roundtrip with random IV."""
        key = FIXTURES["encryption_vectors"][0]["key_hex"]
        plaintext = "python_dynamic_secret_test_42"
        encrypted = encrypt_secret(plaintext, key)
        assert len(encrypted.split(":")) == 3
        decrypted = decrypt_secret(encrypted, key)
        assert decrypted == plaintext

    def test_tamper_detection(self):
        """Python rejects tampered ciphertexts and invalid keys."""
        v = FIXTURES["encryption_vectors"][0]
        iv, tag, ct = v["encrypted"].split(":")

        # Tampered ciphertext
        tampered_ct = f"{iv}:{tag}:ff{ct[2:]}"
        with pytest.raises(Exception):
            decrypt_secret(tampered_ct, v["key_hex"])

        # Tampered tag
        tampered_tag = f"{iv}:00000000000000000000000000000000:{ct}"
        with pytest.raises(Exception):
            decrypt_secret(tampered_tag, v["key_hex"])

        # Wrong key
        wrong_key = "0000000000000000000000000000000000000000000000000000000000000000"
        with pytest.raises(Exception):
            decrypt_secret(v["encrypted"], wrong_key)


class TestSignalNormalizationParity:
    def test_emails(self):
        """Emails normalize and hash identically to fixture vectors (D-14, D-16)."""
        for v in FIXTURES["signal_normalization_vectors"]["emails"]:
            assert normalize_email(v["raw"]) == v["normalized"]
            assert hash_email(v["raw"]) == v["hash"]

    def test_ip_subnets(self):
        """IPv4 subnets mask identically to fixture vectors (D-14, D-16)."""
        for v in FIXTURES["signal_normalization_vectors"]["ip_subnets"]:
            assert mask_ip_subnet(v["raw"]) == v["normalized"]

    def test_user_agents(self):
        """User-Agents normalize and hash identically to fixture vectors (D-14, D-16)."""
        for v in FIXTURES["signal_normalization_vectors"]["user_agents"]:
            assert normalize_user_agent(v["raw"]) == v["normalized"]
            assert hash_user_agent(v["raw"]) == v["hash"]

    def test_device_ids(self):
        """Device IDs normalize and hash identically to fixture vectors."""
        for v in FIXTURES["signal_normalization_vectors"]["device_ids"]:
            assert normalize_device_id(v["raw"]) == v["normalized"]
            assert hash_device_id(v["raw"]) == v["hash"]


class TestMaasTokens:
    def test_tokens_from_fixtures(self):
        """MaaS tokens hash and preview match fixture vectors (D-15)."""
        for v in FIXTURES["maas_token_vectors"]:
            assert hash_maas_token(v["token"]) == v["hash"]
            assert preview_maas_token(v["token"]) == v["preview"]

    def test_generate_maas_token(self):
        """Generated token has correct prefix, length, hash, and preview (D-15)."""
        token, token_hash, preview = generate_maas_token()
        assert token.startswith("maas_live_")
        assert len(token) == 10 + 32  # 42 chars
        assert len(token_hash) == 64
        assert preview.startswith("maas_live_")
        assert "..." in preview
        assert hash_maas_token(token) == token_hash
        assert preview_maas_token(token) == preview


class TestAuditHashChainParity:
    def test_preimages_and_hashes(self):
        """Preimages and entry hashes match fixture vectors (D-06, D-08)."""
        for s in FIXTURES["audit_chain_vectors"]:
            preimage = compute_canonical_preimage(s)
            assert preimage == s["canonical_preimage"]
            entry_hash = compute_entry_hash(s)
            assert entry_hash == s["entry_hash"]

    def test_verify_audit_chain_valid(self):
        """Valid chain from fixtures verifies successfully (D-08)."""
        entries = FIXTURES["audit_chain_vectors"]
        assert verify_audit_chain(entries) is True

    def test_verify_audit_chain_tampered(self):
        """Tampered chains fail verification (D-08)."""
        entries = [dict(s) for s in FIXTURES["audit_chain_vectors"]]

        # Tamper reason in step 2
        entries[1]["reason"] = "Tampered reason string"
        assert verify_audit_chain(entries) is False

        # Reset and tamper step order
        entries = [dict(s) for s in FIXTURES["audit_chain_vectors"]]
        entries[1]["step_number"] = 5
        assert verify_audit_chain(entries) is False

        # Empty chain
        assert verify_audit_chain([]) is False


class TestAuditSanitization:
    def test_sanitize_audit_data(self):
        """Sanitization redacts secrets, hashes emails/UAs/devices, and masks IPs (D-07)."""
        payload = {
            "razorpay_key_secret": "sec_test_secret_12345",
            "password": "merchant_super_secret",
            "buyer": {
                "email": "  Buyer.Name@Example.COM  ",
                "ip": "192.168.1.55",
                "user_agent": "  Mozilla/5.0  (Test) ",
                "device_id": "DEV-1234-ABCD",
            },
            "metadata": {
                "maas_token_hash": "2d55760d323519beca4c779dfaa7a426970ab3f4597cb3a085f4c4650ad1f241",
                "token_preview": "maas_live_e3b0...b855",
                "amount_paise": 50000,
            },
        }

        sanitized = sanitize_audit_data(payload)

        assert sanitized["razorpay_key_secret"] == "[REDACTED]"
        assert sanitized["password"] == "[REDACTED]"
        assert sanitized["buyer"]["email"] == hash_email("buyer.name@example.com")
        assert sanitized["buyer"]["ip"] == "192.168.1.0/24"
        assert sanitized["buyer"]["user_agent"] == hash_user_agent("Mozilla/5.0 (Test)")
        assert sanitized["buyer"]["device_id"] == hash_device_id("dev-1234-abcd")

        assert sanitized["metadata"]["maas_token_hash"] == "2d55760d323519beca4c779dfaa7a426970ab3f4597cb3a085f4c4650ad1f241"
        assert sanitized["metadata"]["token_preview"] == "maas_live_e3b0...b855"
        assert sanitized["metadata"]["amount_paise"] == 50000
